/** Utilitas URL & label sheet — data sheet hanya disimpan per project, bukan global. */

export interface SavedSheet {
  id: string;
  url: string;
  label: string;
  savedAt: string;
  lastOpenedAt: string;
}

const URL_PARAM = "sheet";

function isBrowser() {
  return typeof window !== "undefined";
}

export function deriveSheetLabel(url: string, custom?: string): string {
  if (custom?.trim()) return custom.trim();
  return "Google Sheet";
}

/** Label lama yang digenerate dari ID spreadsheet — boleh diganti judul asli. */
export function isAutoGeneratedSheetLabel(label: string): boolean {
  const t = label.trim();
  if (!t || t === "Google Sheet") return true;
  return /^Sheet [a-zA-Z0-9_-]{6,}/.test(t);
}

export function getSheetFromUrl(): string | null {
  if (!isBrowser()) return null;
  const params = new URLSearchParams(window.location.search);
  const value = params.get(URL_PARAM);
  return value ? decodeURIComponent(value) : null;
}

export function clearSheetFromUrl() {
  if (!isBrowser()) return;
  const params = new URLSearchParams(window.location.search);
  params.delete(URL_PARAM);
  const qs = params.toString();
  const next = qs ? `${window.location.pathname}?${qs}` : window.location.pathname;
  window.history.replaceState(null, "", next);
}

export function truncateUrl(url: string, max = 48): string {
  if (url.length <= max) return url;
  return `${url.slice(0, max)}…`;
}
