import { getPrisma } from "@/lib/db/prisma";
import { isAutoGeneratedSheetLabel, type SavedSheet } from "@/lib/sheet-storage";
import type { Prisma } from "@prisma/client";

function toSavedSheet(row: {
  id: string;
  url: string;
  label: string;
  savedAt: Date;
  lastOpenedAt: Date;
}): SavedSheet {
  return {
    id: row.id,
    url: row.url,
    label: row.label,
    savedAt: row.savedAt.toISOString(),
    lastOpenedAt: row.lastOpenedAt.toISOString(),
  };
}

export async function listUserSheets(userId: string): Promise<SavedSheet[]> {
  const rows = await getPrisma().userSheetConnection.findMany({
    where: { userId },
    orderBy: { lastOpenedAt: "desc" },
  });
  return rows.map(toSavedSheet);
}

export async function getUserLastSheetUrl(userId: string): Promise<string | null> {
  const row = await getPrisma().userSheetConnection.findFirst({
    where: { userId },
    orderBy: { lastOpenedAt: "desc" },
    select: { url: true },
  });
  return row?.url ?? null;
}

export async function upsertUserSheet(
  userId: string,
  url: string,
  label?: string,
  options?: { touchOnly?: boolean; forceLabel?: boolean }
): Promise<SavedSheet> {
  const existing = await getPrisma().userSheetConnection.findUnique({
    where: { userId_url: { userId, url } },
  });

  if (options?.touchOnly) {
    if (!existing) {
      const row = await getPrisma().userSheetConnection.create({
        data: { userId, url, label: "Google Sheet" },
      });
      return toSavedSheet(row);
    }
    const row = await getPrisma().userSheetConnection.update({
      where: { id: existing.id },
      data: { lastOpenedAt: new Date() },
    });
    return toSavedSheet(row);
  }

  if (existing) {
    if (!label) {
      const row = await getPrisma().userSheetConnection.update({
        where: { id: existing.id },
        data: { lastOpenedAt: new Date() },
      });
      return toSavedSheet(row);
    }

    const updateLabel =
      options?.forceLabel || isAutoGeneratedSheetLabel(existing.label);
    const row = await getPrisma().userSheetConnection.update({
      where: { id: existing.id },
      data: {
        lastOpenedAt: new Date(),
        ...(updateLabel ? { label } : {}),
      },
    });
    return toSavedSheet(row);
  }

  const row = await getPrisma().userSheetConnection.create({
    data: { userId, url, label: label ?? "Google Sheet" },
  });
  return toSavedSheet(row);
}

export async function touchUserSheet(userId: string, url: string) {
  await getPrisma().userSheetConnection.updateMany({
    where: { userId, url },
    data: { lastOpenedAt: new Date() },
  });
}

export async function deleteUserSheet(userId: string, sheetId: string) {
  await getPrisma().userSheetConnection.deleteMany({
    where: { userId, id: sheetId },
  });
}

export async function getUserLayout(
  userId: string,
  layoutKey: string
): Promise<unknown | null> {
  const row = await getPrisma().userLayout.findUnique({
    where: { userId_layoutKey: { userId, layoutKey } },
    select: { layoutJson: true },
  });
  return row?.layoutJson ?? null;
}

export async function saveUserLayout(
  userId: string,
  layoutKey: string,
  layoutJson: unknown
) {
  await getPrisma().userLayout.upsert({
    where: { userId_layoutKey: { userId, layoutKey } },
    create: {
      userId,
      layoutKey,
      layoutJson: layoutJson as Prisma.InputJsonValue,
    },
    update: {
      layoutJson: layoutJson as Prisma.InputJsonValue,
    },
  });
}
