#!/bin/bash
set -euo pipefail

READER_PASSWORD="${ANALYTICS_DB_READER_PASSWORD:-iot_reader}"
READER_USER="${ANALYTICS_DB_READER_USER:-iot_reader}"
ESCAPED_PASSWORD="${READER_PASSWORD//\'/\'\'}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${READER_USER}') THEN
      CREATE ROLE ${READER_USER} LOGIN PASSWORD '${ESCAPED_PASSWORD}';
    ELSE
      ALTER ROLE ${READER_USER} WITH PASSWORD '${ESCAPED_PASSWORD}';
    END IF;
  END
  \$\$;

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${READER_USER};

  GRANT USAGE ON SCHEMA public TO ${READER_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${READER_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${READER_USER};

  GRANT USAGE ON SCHEMA education TO ${READER_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA education TO ${READER_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA education GRANT SELECT ON TABLES TO ${READER_USER};
EOSQL
