#!/bin/bash
set -euo pipefail

READER_USER="${MYSQL_ANALYTICS_DB_READER_USER:-retail_reader}"
READER_PASSWORD="${MYSQL_ANALYTICS_DB_READER_PASSWORD:-retail_reader}"
DATABASE="${MYSQL_DATABASE:-retail_analytics}"
ESCAPED_PASSWORD="${READER_PASSWORD//\'/\'\'}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
  CREATE USER IF NOT EXISTS '${READER_USER}'@'%' IDENTIFIED BY '${ESCAPED_PASSWORD}';
  ALTER USER '${READER_USER}'@'%' IDENTIFIED BY '${ESCAPED_PASSWORD}';
  GRANT SELECT ON \`${DATABASE}\`.* TO '${READER_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL
