import { NextRequest, NextResponse } from "next/server";
import { AuthError, requireSessionUser } from "@/lib/session-server";
import {
  deleteUserSheet,
  listUserSheets,
  upsertUserSheet,
} from "@/lib/db/user-sheets";
import { deriveSheetLabel, isAutoGeneratedSheetLabel } from "@/lib/sheet-storage";
import { resolveSheetDisplayName } from "@/lib/sheets";

export const dynamic = "force-dynamic";

async function resolveLabel(
  url: string,
  custom?: string,
  existingLabel?: string
): Promise<string> {
  if (custom?.trim()) return custom.trim();
  const fromGoogle = await resolveSheetDisplayName(url);
  if (fromGoogle !== "Google Sheet") return fromGoogle;
  if (existingLabel && !isAutoGeneratedSheetLabel(existingLabel)) return existingLabel;
  return deriveSheetLabel(url);
}

export async function GET(request: NextRequest) {
  try {
    const user = await requireSessionUser(request);
    const sheets = await listUserSheets(user.id);
    return NextResponse.json({ sheets });
  } catch (error) {
    if (error instanceof AuthError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return NextResponse.json({ error: "Gagal memuat sheet" }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const user = await requireSessionUser(request);
    const body = await request.json();
    const { url, label, touchOnly } = body ?? {};
    if (!url || typeof url !== "string") {
      return NextResponse.json({ error: "URL wajib diisi" }, { status: 400 });
    }

    const trimmed = url.trim();

    if (touchOnly) {
      const sheet = await upsertUserSheet(user.id, trimmed, undefined, { touchOnly: true });
      return NextResponse.json({ sheet });
    }

    const customLabel = typeof label === "string" ? label.trim() : "";
    const existing = (await listUserSheets(user.id)).find((s) => s.url === trimmed);
    const resolved = await resolveLabel(trimmed, customLabel || undefined, existing?.label);

    const sheet = await upsertUserSheet(user.id, trimmed, resolved, {
      forceLabel: Boolean(customLabel),
    });
    return NextResponse.json({ sheet });
  } catch (error) {
    if (error instanceof AuthError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return NextResponse.json({ error: "Gagal menyimpan sheet" }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const user = await requireSessionUser(request);
    const id = request.nextUrl.searchParams.get("id");
    if (!id) {
      return NextResponse.json({ error: "Parameter id wajib" }, { status: 400 });
    }
    await deleteUserSheet(user.id, id);
    return NextResponse.json({ ok: true });
  } catch (error) {
    if (error instanceof AuthError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return NextResponse.json({ error: "Gagal menghapus sheet" }, { status: 500 });
  }
}
